name: AmberTools Installation and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: Create and activate conda environment
      run: |
        conda create --name AmberTools23
        echo "source $CONDA/bin/activate AmberTools23" >> $GITHUB_ENV

    - name: Install AmberTools
      run: |
        conda install -c conda-forge ambertools=23

    - name: Run AmberTools
      run: |
        # Add commands to run AmberTools here
        
