name: AmberTools Installation and Run

on: [push, pull_request] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true 
        python-version: 3.8

    - name: Create conda environment
      run: |
        conda create --name AmberTools23
      shell: bash -l {0}

    - name: Install AmberTools
      run: |
        conda activate AmberTools23
        conda install -c conda-forge ambertools=23
      shell: bash -l {0}

    - name: Run AmberTools
      run: |
        conda activate AmberTools23
        # Add commands to run AmberTools here
      shell: bash -l {0}
